---
name: Bug report
about: Bug reports only, suggestions and new features goes into discussions page
title: ''
labels: ''
assignees: ''

---

## Describe the bug
<!--- A clear and concise description of what the bug is.--->

## Expected behavior
<!--- A clear and concise description of what you expected to happen. --->

## Screenshots
<!--- Add screenshot and illustrate the location of bug on the page.--->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.
