name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'     
        required: true
      releaseNotes:
        description: 'release notes'
        required: false 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.releaseNotes }}
        draft: true
        prerelease: false
